import csv
import math
import unittest
from pathlib import Path


class ExactKinkAnalysisTests(unittest.TestCase):
    path = Path("results/convergence_exact_kink_analysis_v2.csv")

    def test_kink_artifact(self):
        if not self.path.exists():
            self.skipTest("kink artifact is generated by CI")
        rows = list(csv.DictReader(self.path.open(encoding="utf-8")))
        self.assertGreater(len(rows), 0)
        for row in rows:
            for key in ("lambda_exact", "value_gap", "left_derivative", "right_derivative", "derivative_jump", "left_curvature", "right_curvature"):
                self.assertTrue(math.isfinite(float(row[key])))
            self.assertIn(row["transition"], ("C1", "KINK"))
            self.assertLessEqual(float(row["value_gap"]), 1e-7)


if __name__ == "__main__":
    unittest.main()
