import csv
import math
import unittest
from pathlib import Path


class SymbolicRegimeFormulaTests(unittest.TestCase):
    path = Path("results/convergence_symbolic_regime_formulas_v2.csv")

    def test_formula_artifact_is_well_formed(self):
        if not self.path.exists():
            self.skipTest("symbolic formula artifact is generated by CI")
        rows = list(csv.DictReader(self.path.open(encoding="utf-8")))
        self.assertGreater(len(rows), 0)
        self.assertAlmostEqual(float(rows[0]["lambda_start"]), 0.0, places=12)
        self.assertAlmostEqual(float(rows[-1]["lambda_end"]), 1.0, places=12)
        for left, right in zip(rows[:-1], rows[1:]):
            self.assertAlmostEqual(float(left["lambda_end"]), float(right["lambda_start"]), places=12)

    def test_coefficients_and_representation_errors_are_finite(self):
        if not self.path.exists():
            self.skipTest("symbolic formula artifact is generated by CI")
        rows = list(csv.DictReader(self.path.open(encoding="utf-8")))
        for row in rows:
            for key in ("A", "B", "C", "D", "E", "F", "max_interior_error"):
                self.assertTrue(math.isfinite(float(row[key])))
            self.assertLess(float(row["max_interior_error"]), 1e-8)
            self.assertTrue(row["binding_cells"] or row["marginal_cell"])


if __name__ == "__main__":
    unittest.main()
