import csv
import unittest
from pathlib import Path

from model.convergence_analysis import CAPABILITIES, STATES


class ActiveSetRegimeTests(unittest.TestCase):
    def test_regime_artifact_has_expected_schema(self):
        path = Path("results/convergence_active_set_regimes_v2.csv")
        if not path.exists():
            self.skipTest("regime artifact is generated by CI")
        rows = list(csv.reader(path.open(encoding="utf-8")))
        self.assertEqual(rows[0], [
            "regime", "lambda_start", "lambda_end", "active_cell_count",
            "active_cells", "progress_start", "progress_mid", "progress_end"
        ])
        self.assertGreaterEqual(len(rows), 2)

    def test_regime_intervals_are_ordered(self):
        path = Path("results/convergence_active_set_regimes_v2.csv")
        if not path.exists():
            self.skipTest("regime artifact is generated by CI")
        rows = list(csv.DictReader(path.open(encoding="utf-8")))
        starts = [float(r["lambda_start"]) for r in rows]
        ends = [float(r["lambda_end"]) for r in rows]
        self.assertAlmostEqual(starts[0], 0.0, places=12)
        self.assertAlmostEqual(ends[-1], 1.0, places=12)
        for left, right in zip(rows[:-1], rows[1:]):
            self.assertAlmostEqual(float(left["lambda_end"]), float(right["lambda_start"]), places=12)

    def test_active_cells_use_known_state_capability_labels(self):
        path = Path("results/convergence_active_set_regimes_v2.csv")
        if not path.exists():
            self.skipTest("regime artifact is generated by CI")
        allowed = {f"{s}:{c}" for s in STATES for c in CAPABILITIES}
        rows = list(csv.DictReader(path.open(encoding="utf-8")))
        for row in rows:
            for cell in filter(None, row["active_cells"].split(";")):
                self.assertIn(cell, allowed)


if __name__ == "__main__":
    unittest.main()
