import csv
import math
import unittest
from pathlib import Path


class GlobalComparativeStaticsTests(unittest.TestCase):
    path = Path("results/convergence_global_comparative_statics_v2.csv")

    def test_global_artifact_schema(self):
        if not self.path.exists():
            self.skipTest("global artifact is generated by CI")
        rows = list(csv.DictReader(self.path.open(encoding="utf-8")))
        self.assertGreater(len(rows), 0)
        for row in rows:
            for key in ("lambda_exact", "left_derivative", "right_derivative", "derivative_jump", "left_curvature", "right_curvature"):
                self.assertTrue(math.isfinite(float(row[key])))
            self.assertIn(row["transition"], ("C1", "KINK"))
            self.assertIn(row["global_slope_sign"], ("DECREASING", "INCREASING", "SLOPE-CROSSING"))
            self.assertIn(row["curvature_transition"], ("CONVEX", "CONCAVE", "CURVATURE-CHANGE"))


if __name__ == "__main__":
    unittest.main()
