import csv
import math
import unittest
from pathlib import Path


class ExactBreakpointIntersectionTests(unittest.TestCase):
    path = Path("results/convergence_exact_breakpoint_intersections_v2.csv")

    def test_intersections_are_finite_and_bounded(self):
        if not self.path.exists():
            self.skipTest("intersection artifact is generated by CI")
        rows = list(csv.DictReader(self.path.open(encoding="utf-8")))
        self.assertGreater(len(rows), 0)
        for row in rows:
            for key in ("reported_lambda", "exact_intersection", "local_error", "value_left", "value_right", "value_gap"):
                self.assertTrue(math.isfinite(float(row[key])))
            self.assertGreaterEqual(float(row["exact_intersection"]), 0.0)
            self.assertLessEqual(float(row["exact_intersection"]), 1.0)
            self.assertLessEqual(float(row["value_gap"]), 1e-7)


if __name__ == "__main__":
    unittest.main()
