import csv
import math
import unittest
from pathlib import Path


class RegimeDerivativesContinuityTests(unittest.TestCase):
    path = Path("results/convergence_regime_derivatives_continuity_v2.csv")

    def test_partition_and_coefficients(self):
        if not self.path.exists():
            self.skipTest("derivative artifact is generated by CI")
        rows = list(csv.DictReader(self.path.open(encoding="utf-8")))
        self.assertGreater(len(rows), 0)
        self.assertAlmostEqual(float(rows[0]["lambda_start"]), 0.0, places=12)
        self.assertAlmostEqual(float(rows[-1]["lambda_end"]), 1.0, places=12)
        for a, b in zip(rows[:-1], rows[1:]):
            self.assertAlmostEqual(float(a["lambda_end"]), float(b["lambda_start"]), places=12)
        for row in rows:
            for key in ("A", "B", "C", "D", "E", "F", "dPi_start", "dPi_mid", "dPi_end", "ddPi_mid"):
                self.assertTrue(math.isfinite(float(row[key])))


if __name__ == "__main__":
    unittest.main()
