import csv
import math
import unittest
from pathlib import Path


class ActiveSetRegimeMechanicsTests(unittest.TestCase):
    def test_mechanics_artifact_has_expected_schema(self):
        path = Path("results/convergence_active_set_regime_formulas_v2.csv")
        if not path.exists():
            self.skipTest("mechanics artifact is generated by CI")
        rows = list(csv.DictReader(path.open(encoding="utf-8")))
        self.assertGreater(len(rows), 0)
        expected = {
            "regime", "lambda_start", "lambda_end", "active_cell_count",
            "marginal_cells", "binding_feasibility_cells",
            "progress_start", "progress_mid", "progress_end",
        }
        self.assertEqual(set(rows[0]), expected)

    def test_regime_values_are_finite_and_ordered(self):
        path = Path("results/convergence_active_set_regime_formulas_v2.csv")
        if not path.exists():
            self.skipTest("mechanics artifact is generated by CI")
        rows = list(csv.DictReader(path.open(encoding="utf-8")))
        self.assertGreater(len(rows), 0)
        self.assertAlmostEqual(float(rows[0]["lambda_start"]), 0.0, places=12)
        self.assertAlmostEqual(float(rows[-1]["lambda_end"]), 1.0, places=12)
        for left, right in zip(rows[:-1], rows[1:]):
            self.assertAlmostEqual(float(left["lambda_end"]), float(right["lambda_start"]), places=12)
        for row in rows:
            for key in ("lambda_start", "lambda_end", "progress_start", "progress_mid", "progress_end"):
                self.assertTrue(math.isfinite(float(row[key])))
            self.assertGreater(int(row["active_cell_count"]), 0)


if __name__ == "__main__":
    unittest.main()
