import csv
import unittest
from pathlib import Path

class ActiveSetRegimeFormulaTests(unittest.TestCase):
    def test_formula_artifact_schema_when_present(self):
        path = Path('results/convergence_active_set_regime_formulas_v2.csv')
        if not path.exists():
            self.skipTest('formula artifact is generated by CI')
        rows = list(csv.DictReader(path.open(encoding='utf-8')))
        self.assertGreaterEqual(len(rows), 1)
        self.assertEqual(rows[0]['regime'], '0')
        self.assertEqual(rows[-1]['lambda_end'], '1.0')

if __name__ == '__main__':
    unittest.main()
