import csv
import math
import unittest
from pathlib import Path


class ExactRegimeValueFunctionTests(unittest.TestCase):
    path = Path("results/convergence_exact_regime_value_functions_v2.csv")

    def test_artifact_schema_and_partition(self):
        if not self.path.exists():
            self.skipTest("exact-regime artifact is generated by CI")
        rows = list(csv.DictReader(self.path.open(encoding="utf-8")))
        self.assertGreater(len(rows), 0)
        self.assertAlmostEqual(float(rows[0]["lambda_start"]), 0.0, places=12)
        self.assertAlmostEqual(float(rows[-1]["lambda_end"]), 1.0, places=12)
        for a, b in zip(rows[:-1], rows[1:]):
            self.assertAlmostEqual(float(a["lambda_end"]), float(b["lambda_start"]), places=12)

    def test_progress_values_are_finite(self):
        if not self.path.exists():
            self.skipTest("exact-regime artifact is generated by CI")
        rows = list(csv.DictReader(self.path.open(encoding="utf-8")))
        for row in rows:
            for key in ("progress_start", "progress_mid", "progress_end", "left_right_gap"):
                self.assertTrue(math.isfinite(float(row[key])))
            self.assertGreater(int(row["regime"]), -1)
            self.assertTrue(row["active_cells"])


if __name__ == "__main__":
    unittest.main()
